#!/usr/bin/python3

### CSCE 434
### Timing function for SLOCs on Lab 3

import os, time, sys
from datetime import date

def timing_run(executable, flags, path_to_block):
    command_line = "timeout 60s " + executable + " " + flags + " " + path_to_block + " >&/dev/null"

    start_tic = time.perf_counter()
    os.system(command_line)
    stop_tic  = time.perf_counter()
    elapsed_time = stop_tic - start_tic

    if elapsed_time >= 60:
        print("\n--> Execution timeout exceeded!\n")
    return elapsed_time

def run_test(testdir, execname, flags):
    for test in sorted(os.listdir(testdir)):
        if '.i' not in test:
            continue

        result = timing_run(execname, flags, testdir + test)
        result = round(result, 4)
        print("File ", test, ":  " + str(result) + " seconds")

        if result >= 60:
            print("Maximum time exceeded (60 seconds)")
            print("Major efficiency problem.\nTimer stops\n")
            break

def main():
    argc = len(sys.argv)
    if argc != 2:
        print("The timer takes a single argument, the name of your scheduler.\n")
        exit(0)

    execname = sys.argv[1]
    testdir  = "/home/adinapoleon/Compilers/lab3/lab3test/timing_blocks/"
    today    = date.today().strftime("%m-%d-%y")
    hostname = os.uname()[1]

    print("CSCE 434, Lab 3 Timing Test")
    print("Files from '" + testdir + "'.\nEach file run once.\n")

    run_test(testdir, execname, "")  # Lab 3: no extra flags

    print("\nEnd of run.\n")

if __name__ == "__main__":
    main()